window.routes = [
    {"from": "JFK", "to": "LAX", "co2": 500},
    {"from": "JFK", "to": "ORD", "co2": 200},
    {"from": "ORD", "to": "LAX", "co2": 300},
    {"from": "JFK", "to": "ATL", "co2": 250},
    {"from": "ATL", "to": "LAX", "co2": 400},
    {"from": "ATL", "to": "DFW", "co2": 150},
    {"from": "DFW", "to": "LAX", "co2": 200},
    {"from": "ORD", "to": "DFW", "co2": 180},
    {"from": "DFW", "to": "SFO", "co2": 250},
    {"from": "SFO", "to": "LAX", "co2": 100},
    {"from": "JFK", "to": "SFO", "co2": 550},
    {"from": "SFO", "to": "SEA", "co2": 120},
    {"from": "SEA", "to": "LAX", "co2": 200},
    {"from": "JFK", "to": "MIA", "co2": 220},
    {"from": "MIA", "to": "LAX", "co2": 420},
    {"from": "MIA", "to": "ATL", "co2": 160},
    {"from": "MIA", "to": "DFW", "co2": 210},
    {"from": "MIA", "to": "SEA", "co2": 380}
]
