window.routes = [
    {"from": "JFK", "to": "LAX", "co2": 500},
    {"from": "JFK", "to": "ORD", "co2": 200},
    {"from": "ORD", "to": "LAX", "co2": 300},
    {"from": "JFK", "to": "ATL", "co2": 250},
    {"from": "ATL", "to": "LAX", "co2": 400},
    {"from": "ATL", "to": "DFW", "co2": 150},
    {"from": "DFW", "to": "LAX", "co2": 200},
    {"from": "ORD", "to": "DFW", "co2": 180},
    {"from": "DFW", "to": "SFO", "co2": 250},
    {"from": "SFO", "to": "LAX", "co2": 100},
    {"from": "JFK", "to": "SFO", "co2": 550},
    {"from": "SFO", "to": "SEA", "co2": 120},
    {"from": "SEA", "to": "LAX", "co2": 60},
    {"from": "ARN", "to": "ATL", "co2": 200},
    {"from": "BMA", "to": "ARN", "co2": 430},
    {"from": "YOW", "to": "LAX", "co2": 310},
    {"from": "SEA", "to": "IAD", "co2": 220},
    {"from": "DMM", "to": "YOW", "co2": 550},
]
